### ISSUE TITLE
Wrong version of python packages fetched due to odev python version imposed

### ISSUE THREAD

**Issue by lse-odoo** [odoo-odev/odev#24]
## Classification

Is this a bug report or a request for a missing feature (choose one):

- [x] Bug report
- [ ] New feature request / enhancement

What is this issue's criticality (choose one)?

- [ ] Quality of life
- [ ] Nice to have
- [x] Blocking
- [ ] Critical

## Issue description

What happened?

- *Give as much detail as you can to help us understand the issue you faced.*

I just installed odev and tried to create a database.
Important to note that I am on latest ubuntu version 24.04 (Noble) which comes with python3.12.
As I was having the error:
`[~] Missing interpreter for python 3.10, please install it using your distribution's package manager and try again`
I installed a python3.10 version on the computer and was correctly used as my master environment.
However, when trying to install odoo's dependencies, there is the following issue:
```txt
Collecting gevent==21.8.0
  Using cached gevent-21.8.0.tar.gz (6.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [45 lines of output]
      Compiling src/gevent/resolver/cares.pyx because it changed.
      [1/1] Cythonizing src/gevent/resolver/cares.pyx
      performance hint: src/gevent/libev/corecext.pyx:1325:0: Exception check on '_syserr_cb' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare '_syserr_cb' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on '_syserr_cb' to allow an error code to be returned.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cdef tuple integer_types
      
      if sys.version_info[0] >= 3:
          integer_types = int,
      else:
          integer_types = (int, long)
                                ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:60:26: undeclared name not builtin: long
      Compiling src/gevent/libev/corecext.pyx because it changed.
      [1/1] Cythonizing src/gevent/libev/corecext.pyx
      Traceback (most recent call last):
        File "/home/loan/odev/virtualenvs/master/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/loan/odev/virtualenvs/master/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/loan/odev/virtualenvs/master/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-po5ucfg8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-po5ucfg8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-po5ucfg8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-po5ucfg8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 50, in <module>
        File "/tmp/pip-install-prx39u0n/gevent_6ccee9d6c9e9468ab14fe0102fdb9b5f/_setuputils.py", line 237, in cythonize1
          new_ext = cythonize(
        File "/tmp/pip-build-env-po5ucfg8/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1109, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-po5ucfg8/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1256, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: src/gevent/libev/corecext.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

While looking at Odoo's requirement.txt file on gevent installation:
https://github.com/odoo/odoo/blob/64b9eaf07cf5101e39ec1a59454572d957e1fa61/requirements.txt#L20-L22
We can see that it determines the used version based on the python version. As we forced python3.10, we mistakenly use the "jammy" one instead of the intended "noble".

If I manually install the "noble" version, then the error does not happen

- *What command did you run when facing the issue? What happened then?*
`odev create odev-test`

**Comment by brinkflew** [comment]
This is possibly fixed by #19 in which unit tests failed for the same reason.
@lse-odoo can you try running `odev update` and check if the issue persists?

Side note, I seem to understand that you downgraded your main python interpreter from 3.12 to 3.10? This is not necessary nor is it recommended, as many system-wide and pre-installed tools depend on the installed python version. Installing `python3.10` so that it exists somewhere in the path is enough for `virtualenv` to use it while keeping the base interpreter as 3.12.

**Comment by lse-odoo** [comment]
@brinkflew 
I ran odev update but the issue persist (in a different way). Now I have the error: 
`[~] Missing interpreter for python 3.10, please install it using your distribution's package manager and try again 
 python.py:141`.
It looks to come from:
```
      File "/home/loan/Odoo/odev/odev/commands/database/create.py", line 176, in initialize_database                                                                                                                                
        process.run(args=args, progress=self.odoobin_progress)                                                                                                                                                                      
      File "/home/loan/Odoo/odev/odev/common/odoobin.py", line 537, in run                                                                                                                                                          
        self.prepare_odoobin()                                                                                                                                                                                                      
      File "/home/loan/Odoo/odev/odev/common/odoobin.py", line 410, in prepare_odoobin                                                                                                                                              
        with spinner(f"Preparing virtual environment {self.venv.name!r}"):                                                                                                                                                          
      File "/home/loan/Odoo/odev/odev/common/odoobin.py", line 137, in venv                                                                                                                                                         
        self._venv = PythonEnv(self.venv_path, self._get_python_version())                                                                                                                                                          
      File "/home/loan/Odoo/odev/odev/common/python.py", line 63, in __init__                                                                                                                                                       
        logger.info(version, stack_info=True)  # -> (added by me) printing 3.10
```
which looks to happen as the highest python version set in the mapper is 3.10:
https://github.com/odoo-odev/odev/blob/main/odev/common/odoobin.py#L58

I did install python3.10 using apt-get. I think it just kept both of them and 3.12 as the default one and 3.10 if explicitly asked for. To avoid bias I removed the 3.10 install so that only 3.12 remain
